# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Article:
  fields:
    default: is_mained, published_at, title, author, guid, blog_id, link, summary, description, blog
    form: is_mained, published_at, title, author, guid, blog_id, link, summary, description, blog
  order_by: 
  relationships: blog
  filters: created_at
  search: title
  application: chebytoday

Blog:
  fields:
    default: author, title, link, yandex_rating, friends, rss_link, articles_count, user_id, user
    form: author, title, link, yandex_rating, friends, rss_link, articles_count, user_id, user
  order_by: 
  relationships: articles, user
  filters: created_at
  search: title
  application: chebytoday

Politic:
  fields:
    default: name, title, desc
    form: name, title, desc
  order_by: 
  relationships: 
  filters: created_at
  search: name, title
  application: chebytoday

Twit:
  fields:
    default: text, favorited, place, retweeted_status, geo, truncated, source, contributors, coordinated, twit_user_id, in_reply_to_user_id, in_reply_to_status_id, in_reply_to_screen_name, twit_user
    form: text, favorited, place, retweeted_status, geo, truncated, source, contributors, coordinated, twit_user_id, in_reply_to_user_id, in_reply_to_status_id, in_reply_to_screen_name, twit_user
  order_by: 
  relationships: base_tags, tag_taggings, taggings, tags, twit_user
  filters: created_at
  search: 
  application: chebytoday
  

TwitUser:
  fields:
    # default: screen_name, profile_image_url, friends_count, statuses_count, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
    default: screen_name, following, state, is_anounced, location, is_cheboksary, source, cheboksary_source
    form: screen_name, profile_image_url, friends_count, statuses_count, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
    show: screen_name, is_location_cheboksary?, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
  order_by: 
  relationships: twits
  filters: following, is_anounced, state, is_cheboksary
  search: name, location, source, cheboksary_source
  application: chebytoday
  options:
    default_action_on_item: show
    per_page: 50

Twitter:
  fields:
    # default: screen_name, profile_image_url, friends_count, statuses_count, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
    default: screen_name, name, state, list_state, admin_links, location, source, anounced_at, created_at
    # form: screen_name, profile_image_url, friends_count, statuses_count, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
    # show: screen_name, is_location_cheboksary?, following, is_cheboksary, state, favourites_count, followers_count, listed_count, name, is_anounced, followed_at, location, source, cheboksary_source
    options:
      selectors: state, list_state

  actions:
    edit: go_to_twitter
    show: go_to_twitter
      
  order_by: -created_at
  relationships: 
  filters: state, list_state
  search: screen_name, name, location, source
  application: chebytoday
  options:
    action_after_save: index
    default_action_on_item: edit
    per_page: 50

User:
  fields:
    default: email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, nick, role, status
    form: email, reset_password_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, nick, role, status
  order_by: 
  relationships: articles, blogs
  filters: created_at
  search: 
  application: chebytoday

